const APP_NAME = "CYBERCORE";
const APP_VERSION = "0.2.20";
const CPU_CLOCK_INTERVAL = 100;
const TIMER_IRQ = 0;
const KEYBOARD_IRQ = 1;
const SCHED_IRQ = 2;
var _CPU;
var _Memory;
var _MemManager;
var _Scheduler;
let singleStep = false;
let canStep = true;
var _OSclock = 0;
var _Mode = 0;
var _Canvas;
var _DrawingContext;
var _DefaultFontFamily = "sans";
var _DefaultFontSize = 13;
var _FontHeightMargin = 4;
var _Trace = true;
var _Kernel;
var _KernelInterruptQueue;
var _KernelInputQueue = null;
var _KernelBuffers = null;
var _StdIn;
var _StdOut;
var _Console;
var _OsShell;
var _SarcasticMode = false;
var MAX_MEMORY = 768;
var _krnKeyboardDriver;
var _hardwareClockID = null;
var Glados = null;
var _GLaDOS = null;
var onDocumentLoad = function () {
    TSOS.Control.hostInit();
};
//# sourceMappingURL=globals.js.map